# Generated by Django 6.0.5 on 2026-05-06 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publicacion_descripcion_publicacion_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitado_en', models.DateTimeField(auto_now_add=True)),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.publicacion')),
            ],
            options={
                'unique_together': {('publicacion', 'comerciante')},
            },
        ),
    ]
