# Generated by Django 6.0.5 on 2026-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visitapublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
