# Generated by Django 6.0.5 on 2026-05-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicacion_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='stock_unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
