# Generated by Django 6.0.5 on 2026-05-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_negociacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negociacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='negociacion',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
