# Generated by Django 6.0.5 on 2026-05-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='push_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
