# Generated by Django 6.0.5 on 2026-05-13 04:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_perfil_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='push_token',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
