# Generated by Django 6.0.5 on 2026-06-09 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_negociacion_estado_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='negociacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='core.negociacion'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='push_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
