# Generated by Django 6.0.5 on 2026-07-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notificacion_negociacion_perfil_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='stock_unidad',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='peso_kg_unidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
