# Generated by Django 6.0.5 on 2026-07-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_publicacion_stock_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='cantidad_minima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
