# Generated by Django 6.0.5 on 2026-07-03 07:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_publicacion_cantidad_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='documento_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_cedula',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_cedula'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ocr_texto_crudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='capacidad_entrega',
            field=models.CharField(blank=True, choices=[('retiro_finca', 'Solo retiro en finca'), ('casco_urbano', 'Llevo al casco urbano'), ('transporte_propio', 'Transporte propio al destino')], max_length=20),
        ),
    ]
